version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: portfolio-db
    restart: always
    environment:
      POSTGRES_USER: portfolio_user
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: portfolio
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - portfolio-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: portfolio-backend
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - portfolio-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: portfolio-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8501:8501"
    networks:
      - portfolio-net

volumes:
  postgres_data:

networks:
  portfolio-net:
    driver: bridge
